layout_spectrum: 0.8345864
typography_spectrum: 0.7913534
color:
  saturation: 0.06667522
  lightness: 0.4114407
  brandStrength: 1
  brandColors:
    - '#BC0A29'
    - '#010000'
    - '#555859'
    - '#202122'
    - '#CF5167'
  rhythmicContrast: 0.4595077
name: Mind Body Synergy 4Life
