collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
typography_spectrum: 0.7913534
color:
  saturation: 0.06667522
  brandStrength: 1
  lightness: 0.6710526
  brandColors:
    - '#BC0A29'
    - '#010000'
    - '#555859'
    - '#202122'
    - '#CF5167'
  rhythmicContrast: 0.4595077
layout_spectrum: 0.8345864
name: Mind Body Synergy 4Life
